config/routes.rb
Rails.application.routes.draw do
  
  # ユーザー用devise
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  
  # 管理者用devise
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  # ユーザ側ルーティング
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about', as: 'about'
    # マイページ・ユーザーページ用
    resources :users, only: [:show, :update, :destroy]
    get 'mypage' => "users#mypage"
    get 'mypage/edit' => "users#edit"
    get 'unsubscribe' => "users#unsubscribe"
    get 'mypage/favorites' => "users#favorite"
    # 投稿
    resources :posts do
      # コメント用
      resources :post_comments, only: [:create, :destroy]
      # ブックマーク用
      resource :favorites, only: [:create, :destroy]
      # 通報用
      resource :reports, only: [:new, :create]
      get 'reports/complete' => "reports#complete"
    end
    # キーワード検索用
    get 'search' => "posts#search"
    # 地方区分絞り込み用
    resources :regions, only: [:index]
    # 都道府県絞り込み用
    resources :prefectures, only: [:index]
    # タグ検索用
    resources :tags, only: [:index]
    # 通報用
    resources :reports, only: [:new, :create]
  end
  
  # 管理者側ルーティング
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :tags, except: [:show, :new]
    resources :reports, only: [:show, :update]
  end
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  # モデル間のアソシエーション
  has_many :post_tags, dependent: :destroy, foreign_key: 'tag_id'
  # タグは投稿を複数持つ。post_tagsを通して参照可能
  has_many :posts, through: :post_tags
  
  # バリデーション 管理者側：タグ名が重複していないか確認
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def index
    @tags = Tag.page(params[:page]).per(18)
    @tag = Tag.new
  end

  def create
    tag = Tag.new(tag_params)
    if tag.save
      flash[:notice] = "タグを追加しました。"
      redirect_to admin_tags_path
    else
      @tags = Tag.page(params[:page])
      @tag = Tag.new
      flash[:alert] = "タグを追加できませんでした。"
      render :index
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    tag = Tag.find(params[:id])
    if tag.update(tag_params)
      flash[:notice] = "タグを編集しました。"
      redirect_to admin_tags_path
    else
      @tag = Tag.find(params[:id])
      flash[:alert] = "タグを更新できませんでした。"
      render :edit
    end
  end

  def destroy
    tag = Tag.find(params[:id])
    if tag.destroy
      flash[:notice] = "タグを削除しました。"
      redirect_to admin_tags_path
    else
      @tags = Tag.page(params[:page])
      @tag = Tag.new
      flash[:alert] = "タグを削除できませんでした。"
      render :index
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class="row mb-5">
  <div class="col-md-12 mx-auto">
    <h1 class="header-option adm-header">タグ編集</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-5 mx-auto mt-5">
    <%= form_with model: @tag, url: admin_tag_path, method: :patch do |f| %>
      <div class="card card-border-bottom-option option-center mt-4">
        <h4 class="card-title basic-font">
          <%= f.label :name, "タグ名" %>
          <%= f.text_field :name, placeholder: "ここに入力", class: "tag-input-form mt-3" %>
        </h4>

        <div class="card-body pb-5">
          <%= f.submit "変更する", class: "btn btn-option" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="row mb-5">
  <div class="col-md-12">
    <h1 class="header-option adm-header">タグ一覧・追加</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-4 mb-5">
    <%= form_with model: @tag, url: admin_tags_path, method: :post do |f| %>
      <h4 class="header-option adm-header">
        タグ追加
      </h4>

      <div class="card card-border-bottom-option option-center mt-4">
        <h4 class="card-title basic-font">
          <%= f.label :name, "タグ名" %>
          <%= f.text_field :name, placeholder: "ここに入力", class: "tag-input-form mt-3" %>
        </h4>

        <div class="card-body pb-5">
          <%= f.submit "追加する", class: "btn btn-option" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-8">
    <% if @tags.count == 0 %>
      <p class="basic-font">
        タグは登録されていません。
      </p>
    <% else %>
      <h4 class="header-option adm-header">
        タグ一覧
      </h4>
      <div class="row mt-4">
        <% @tags.each do |tag| %>
          <div class="col-md-4">
            <div class="card tag-card-option mb-3">
              <div class="card-header text-12rem text-bold card-header-option">
                <i class="fa-sharp fa-solid fa-tag"></i>
                <%= tag.name %>
              </div>
              <div class="card-body">
                <span class="border-all-option-edit">
                  <%= link_to edit_admin_tag_path(tag.id), class: "text-black", method: :get do %>
                    <i class="fa-sharp fa-solid fa-pen-to-square"></i>
                  <% end %>
                </span>

                <span class="border-all-option-delete">
                  <%= link_to admin_tag_path(tag.id), class: "text-red", "data-confirm" => "削除してよろしいですか？", method: :delete do %>
                    <i class="fa-sharp fa-solid fa-trash-can"></i>
                  <% end %>
                </span>
              </div>
            </div>
          </div>
        <% end %>

        <div class="mt-5">
          <%= paginate @tags %>
        </div>
    <% end %>
  </div>
</div>