config/routes.rb
Rails.application.routes.draw do
  
  # ユーザー用devise
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  
  # 管理者用devise
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  # ユーザ側ルーティング
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about', as: 'about'
    # マイページ・ユーザーページ用
    resources :users, only: [:show, :update, :destroy]
    get 'mypage' => "users#mypage"
    get 'mypage/edit' => "users#edit"
    get 'unsubscribe' => "users#unsubscribe"
    get 'mypage/favorites' => "users#favorite"
    # 投稿
    resources :posts do
      # コメント用
      resources :post_comments, only: [:create, :destroy]
      # ブックマーク用
      resource :favorites, only: [:create, :destroy]
      # 通報用
      resource :reports, only: [:new, :create]
      get 'reports/complete' => "reports#complete"
    end
    # キーワード検索用
    get 'search' => "posts#search"
    # 地方区分絞り込み用
    resources :regions, only: [:index]
    # 都道府県絞り込み用
    resources :prefectures, only: [:index]
    # タグ検索用
    resources :tags, only: [:index]
    # 通報用
    resources :reports, only: [:new, :create]
  end
  
  # 管理者側ルーティング
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :tags, except: [:show, :new]
    resources :reports, only: [:show, :update]
  end
  
end

app/models/post.rb
class Post < ApplicationRecord

  # 画像を投稿できるようにする
  has_one_attached :image

  # モデル間のアソシエーション
  belongs_to :user
  belongs_to :region

  has_many :reports, foreign_key: 'post_id' # 通報は履歴として残す
  has_many :post_comments,    dependent: :destroy, foreign_key: 'post_id'
  has_many :favorites,        dependent: :destroy, foreign_key: 'post_id'
  has_many :post_tags,        dependent: :destroy, foreign_key: 'post_id'
  has_many :post_prefectures, dependent: :destroy, foreign_key: 'post_id'

  # 投稿は複数のタグと都道府県を持つ。それぞれpost_tagsとpost_prefecturesを通じて参照可能
  has_many :tags,        through: :post_tags
  has_many :prefectures, through: :post_prefectures

  # 親子孫関係にあるテーブルを一度に保存する(無くても可)
  accepts_nested_attributes_for :post_tags
  accepts_nested_attributes_for :post_prefectures

  # バリデーション
  validates :title, presence: true
  validates :body, presence: true
  validates :region_id, presence: true
  validates :user_id, presence: true

  # 投稿画像
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/post-image.png')
      image.attach(io: File.open(file_path), filename: 'post-image.png', content_type: 'image/png')
    end
    image
  end

  # キーワード検索でユーザが入力した値と部分一致するデータを取得
  def self.search(keyword)
    Post.where(['body like?', "%#{keyword}%"])
  end

  # 同じユーザが同じ投稿に複数お気に入りできないよう、user_idがFaboritesテーブルに存在するかどうか
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # タグ編集メソッド(destroy_allを使うタイプ)
  def save_tag(post_tags_params)
    if post_tags_params.empty?
      post_tags.destroy_all
    end
    # 送信されたタグが空でない場合、その投稿の既存のタグをすべて削除
    unless post_tags_params.empty?
      self.post_tags.destroy_all

      post_tags_params.each do |new|
        # 送信された各タグについて、PostTagモデルから既存のタグを検索し、存在しない場合は新しく作成
        new_post_tag = PostTag.find_or_create_by(post_id: :id, tag_id: new)

        #同じタグを登録するとエラーになるので、include?で回避
        unless self.post_tags.include?(new_post_tag)
          # 左のオブジェクト(post_tags)に右のオブジェクト(new_post_tag)を追加
          self.post_tags << new_post_tag
        end
      end
    end
  end

  # 都道府県編集メソッド(タグと同様)
  def save_prefecture(prefectures_params)
    if prefectures_params.empty?
      post_prefectures.destroy_all
    end

    unless prefectures_params.empty?
      self.post_prefectures.destroy_all

      prefectures_params.each do |new|
        new_post_prefecture = PostPrefecture.find_or_create_by(post_id: :id, prefecture_id: new)

        #同じ都道府県を登録するとエラーになるので、include?で回避
        unless self.post_prefectures.include?(new_post_prefecture)
          self.post_prefectures << new_post_prefecture
        end
      end
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.page(params[:page]).per(20)
  end

  def show
    @post = Post.find(params[:id])
    @post_comments = @post.post_comments.all
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:notice] = "投稿を削除しました。"
      redirect_to admin_posts_path
    else
      @post = Post.find(params[:id])
      @post_comments = @post.post_comments.all
      flash[:alert] = "投稿の削除に失敗しました。"
      render :show
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="row mb-5">
  <div class="col-md-12">
    <h1 class="header-option adm-header">投稿一覧</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mx-auto">
    <% if @posts.count == 0 %>
      <p class="text-15rem">
        投稿はありません。
      </p>
    <% else %>
      <table class="table ellipsis">
        <thead class="text-center">
          <tr>
            <th style="width: 15%">投稿ID</th>
            <th style="width: 20%">投稿日時</th>
            <th style="width: 30%">タイトル</th>
            <th style="width: 30%">投稿者</th>
          </tr>
        </thead>

        <% @posts.each do |post| %>
        <tbody>
          <tr>
            <td class="text-center">
              <%= post.id %>
            </td>
            <td class="text-center">
              <%= l post.created_at %>
            </td>
            <td>
              <%= link_to post.title, admin_post_path(post.id), class: "link-option" %>
            </td>
            <td>
              <%= post.user.name %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    <% end %>
  </div>

  <div class="mt-5">
    <%= paginate @posts %>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="row mb-5">
  <div class="col-md-12">
    <h1 class="header-option adm-header">投稿詳細</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-10 mx-auto mb-5">
      <h2 class="header-option adm-header">投稿タイトル</h2>
      <h2 class="transparent-option-pd basic-font">
        <%= @post.title %>
      </h2>
    </div>
  </div>


  <div class="row mx-auto">
    <div class="col-md-10 mx-auto">
      <div class="row">
        <div class="col-md-4 mb-5">
          <h6 class="header-option adm-header">
            投稿ID ：
            <%= @post.id %>
          </h6>
        </div>

        <div class="col-md-8 mb-5">
          <h6 class="header-option adm-header">
            投稿日時 ：
            <%= l @post.created_at %>
          </h6>
        </div>
      </div>

      <div class="row mx-auto mb-5">
        <h4 class="header-option adm-header">投稿者</h4>
        <div class="transparent-option-pd text-15rem">
          <%= link_to @post.user.name, admin_user_path(@post.user_id), class: "link-option-15rem" %>
        </div>
      </div>

      <!--投稿画像-->
      <div class="row mb-5">
        <div class="col-md-6 mx-auto">
          <div class="img-resize-show">
            <%= image_tag @post.get_image %>
          </div>
        </div>
      </div>

      <h5 class="header-option adm-header">本文</h5>
      <div class="transparent-option-pd text-15rem">
        <%= safe_join(@post.body.split("\n"),tag(:br)) %>
      </div>

      <h5 class="header-option adm-header mt-5">タグ</h5>
      <div class="transparent-option-pd text-12rem">
        <% if @post.post_tags.present? %>
          <% @post.post_tags.each do |pt| %>
            <span class="mr-3">
              <%= pt.tag.name %>
            </span>
          <% end %>
        <% else %>
          <div class="text-12rem text-white">選択されていません</div>
        <% end %>
      </div>

      <h5 class="header-option adm-header mt-5">地方区分</h5>
      <div class="transparent-option-pd text-12rem">
        <%= @post.region.region_name %>
      </div>

      <h5 class="header-option adm-header mt-5">都道府県</h5>
      <div class="transparent-option-pd text-12rem">
        <% if @post.post_prefectures.present? %>
          <% @post.post_prefectures.each do |pp| %>
            <%= pp.prefecture.prefecture_name %>
          <% end %>
        <% else %>
          <div class="text-12rem text-white">選択されていません</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="comment-border mt-5 mb-4"></div>

<div class="row mx-auto">
  <div class="col-md-7 mx-auto">
    <h5 class="header-option adm-header">
      コメント一覧
    </h5>
  </div>
</div>

<div class="row mx-auto">
  <div class="col-md-6 mx-auto mb-5">
    <% if @post_comments.present? %>
      <% @post_comments.each do |post_comment| %>
        <div class="comment-option">
          <div class="comment-data">
            <%= l post_comment.created_at, format: :short %>
          </div>

          <div class="comment-body">
            <%= safe_join(post_comment.comment.split("\n"),tag(:br)) %>
          </div>

          <div class="mt-2 option-right">
            <%= link_to post_comment.user.name, admin_user_path(post_comment.user_id), class: "comment-name comment-omit-adm" %>
            <span>
              <%= link_to "削除", admin_post_post_comment_path(post_comment.post, post_comment), method: :delete, "data-confirm" => "コメントを削除しますか？", class: "btn comment-delete" %>
            </span>
          </div>
        </div>

        <div class="comment-border"></div>
      <% end %>
    <% else %>
      <p class="basic-font ml-3">コメントはありません。</p>
    <% end %>
  </div>
</div>


<div class="my-5 option-center">
  <%= link_to "投稿を削除する", admin_post_path(@post.id), method: :delete, "data-confirm" => "本当によろしいですか？", class: "btn danger-btn" %>
</div>