config/routes.rb
Rails.application.routes.draw do
  
  # ユーザー用devise
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  
  # 管理者用devise
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  # ユーザ側ルーティング
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about', as: 'about'
    # マイページ・ユーザーページ用
    resources :users, only: [:show, :update, :destroy]
    get 'mypage' => "users#mypage"
    get 'mypage/edit' => "users#edit"
    get 'unsubscribe' => "users#unsubscribe"
    get 'mypage/favorites' => "users#favorite"
    # 投稿
    resources :posts do
      # コメント用
      resources :post_comments, only: [:create, :destroy]
      # ブックマーク用
      resource :favorites, only: [:create, :destroy]
      # 通報用
      resource :reports, only: [:new, :create]
      get 'reports/complete' => "reports#complete"
    end
    # キーワード検索用
    get 'search' => "posts#search"
    # 地方区分絞り込み用
    resources :regions, only: [:index]
    # 都道府県絞り込み用
    resources :prefectures, only: [:index]
    # タグ検索用
    resources :tags, only: [:index]
    # 通報用
    resources :reports, only: [:new, :create]
  end
  
  # 管理者側ルーティング
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :tags, except: [:show, :new]
    resources :reports, only: [:show, :update]
  end
  
end

app/models/report.rb
class Report < ApplicationRecord
  # モデル間のアソシエーション
  # 外部キーのnilを許可する
  belongs_to :post, optional: true
  
  # バリデーション
  validates :reason, presence: true
  validates :body, presence: true

  # 通報理由
  enum reason: {
    illegal: 0,                       #違法行為
    offensive_content: 1,             #攻撃的な内容
    promote_discrimination: 2,        #差別助長
    spam: 3,                          #スパム
    impersonation: 4,                 #なりすまし
    copyright: 5,                     #著作権
    personal_information: 6,          #個人情報(肖像権含む)
    other_violations_of_the_terms: 7, #その他利用規約違反
    other_inappropriate_content: 8    #その他不適切なコンテンツ
  }
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController

  def show
    @report = Report.find(params[:id])
  end

  def update
    report = Report.find(params[:id])
    if report.update(report_params)
      flash[:notice] = "対応ステータスを更新しました。"
      redirect_to admin_root_path
    else
      @report = Report.find(params[:id])
      flash[:alert] = "ステータスの更新に失敗しました。"
      render :show
    end
  end

  private

  def report_params
    params.require(:report).permit(:is_handled)
  end

end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>通報一覧</h1>
    </div>
  </div>
  
  <div class="row">
    <div class="col">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>通報ID</th>
            <th>通報日時</th>
            <th>通報理由</th>
            <th>対応確認</th>
          </tr>
        </thead>
        
        <tbody>
        <% @reports.each do |report| %>
          <tr>
            <td>
              <%= report.id %>
            </td>
            <td>
              <a href="reports/<%= report.id %>">
                <%= l report.created_at %>
              </a>
            </td>
            <td>
              <%= report.reason_i18n %>
            </td>
            <td>
              <% if report.is_handled == false %>
                <p class="text-danger">未対処</p>
              <% else %>
                <p class="taxt-dark">対処済み</p>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/reports/show.html.erb
<div class="row mb-5">
  <div class="col-md-12">
    <h1 class="header-option adm-header">通報詳細</h1>
  </div>
</div>

<div class="row mx-auto">
  <div class="col-md-8 mx-auto">
    <div class="row">
      <div class="col-md-4 mb-5">
        <h6 class="header-option adm-header">
          通報ID ：
          <%= @report.id %>
        </h6>
      </div>

      <div class="col-md-8 mb-5">
        <h6 class="header-option adm-header">
          通報日時 ：
          <%= l @report.created_at %>
        </h6>
      </div>
    </div>

    <h4 class="header-option adm-header">該当投稿タイトル</h4>
    <div class="transparent-option-pd text-12rem">
      <% if @report.post.present? %>
        <%= link_to @report.post.title, admin_post_path(@report.post_id), class: "link-option" %>
      <% else %>
        投稿ID:<%= @report.post_id %> / 削除済みの投稿
      <% end %>
    </div>

    <h4 class="header-option adm-header mt-5">通報理由</h4>
    <div class="transparent-option-pd text-12rem">
      <%= @report.reason_i18n %>
    </div>

    <h4 class="header-option adm-header mt-5">通報理由詳細</h4>
    <div class="transparent-option-pd text-15rem">
      <%= safe_join(@report.body.split("\n"),tag(:br)) %>
    </div>

    <h4 class="header-option adm-header mt-5">対応確認</h4>
    <%= form_with model: @report, url: admin_report_path, method: :patch do |f| %>
      <div class="text-12rem mt-3 mb-5 px-3">
        <span class="bold-red">
          <%= f.radio_button :is_handled, false %>
          <%= f.label :is_handled, "未対処" %>
        </span>
        <span>　</span>
        <span class="bold-bl">
          <%= f.radio_button :is_handled, true %>
          <%= f.label :is_handled, "対処済み" %>
        </span>
        <span>　　</span>
        <%= f.submit "変更を保存", class: "btn btn-option" %>
      </div>
    <% end %>
  </div>
</div>